name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Make gradlew executable
        run: chmod +x ./mvnw
      - name: Run build and tests with Maven
        run: ./mvnw test
  container:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: 02ten/marketplace-seller-service:${{ github.sha }}
  manifest:
    needs: [container]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        run: |
          git clone https://github.com/02ten/marketplace-k8s-config.git
        env:
          GITHUB_TOKEN: ${{ secrets.CONFIG_TOKEN }}
      - name: Update yaml
        working-directory: ./marketplace-k8s-config
        run: |
          sed -i 's/image: 02ten\/marketplace-seller-service:.*/image: 02ten\/marketplace-seller-service:${{ github.sha }}/g' application/seller-service/seller-service.yaml
          git config --global user.email "89169604848t@gmail.com"
          git config --global user.name "02ten"
          git add .
          git commit -m "Update seller-service image version"
          git push -u https://${{ secrets.USERNAME }}:${{ secrets.CONFIG_TOKEN }}@github.com/02ten/marketplace-k8s-config.git main
        env:
          GITHUB_TOKEN: ${{ secrets.CONFIG_TOKEN }}